### ISSUE TITLE
Editing educational

### ISSUE THREAD

**Issue by bianchimro** [C2DH/ww1-visualeditor#36]
editor to add manuals
each manual is a story

show current manuals
reorder manuals
edit manual
create manual

manual editing is like module editing (no preview)

see mockup, but:

- no related theme, but "cover" as the theme or chapter cover (object cover)
- suggested activities are fixed  (cannot add items dynamically, show all inputs)
- description of suggested activities should have medium editor
- related object (bottom-right in mockup= with object picker (image), renders image + title as caption, with link to collection

**Comment by uf0** [comment]
[MOCKUP EDUCATIONAL SECTION.pdf](https://github.com/C2DH/ww1-visualeditor/files/1355957/MOCKUP.EDUCATIONAL.SECTION.pdf)

**Comment by uf0** [comment]
[add educational.pdf](https://github.com/C2DH/ww1-visualeditor/files/1355961/add.educational.pdf)
