### ISSUE TITLE
Image bounding box picker

### ISSUE THREAD

**Issue by bianchimro** [C2DH/ww1-visualeditor#4]
Implement a form widget to be used with redux-form for choosing an image bounding box.
The picker should open in a modal (bs4/reactstrap) and take a source image as a parameter (the image shown on the preview for choosing the bounding box)
The return value should be an array of 4 points
The picker should implement a control to reset the box to the whole image size and a "cancel" control to cancel the user selection

**Comment by gffuma** [comment]
https://fengyuanchen.github.io/cropperjs/

**Comment by gffuma** [comment]
https://github.com/jerryshew/react-image-cropper
